### PR TITLE
Upstream update November 1

### PR DESCRIPTION
**Pull request by Qard**
This also includes everything in #124.

Skipped (README.md):
 - nodejs/node@fa939f0cf59fd
 - nodejs/node@46ca1775a31d5

New upstream HEAD:
 - nodejs/node@94b2be7a96a5

### CODE REVIEW

**Review by aqrln — APPROVED** [review]

**Review by addaleax — APPROVED** [review]
LGTM

The test are failing because of the new (?) linter execution in Node.js, I guess

**Comment by Qard** [comment]
Seems to have a bunch of linting failures locally. I'll try a nodejs build to see how it compares. https://gist.github.com/Qard/5d6932944602f2579843469c722f11ed

**Comment by Qard** [comment]
There's some lint errors for lack of documentation of worker errors and there's some from our top-level md files. We can probably at least ignore the top-level ones for now.

More concerning though is that almost all the http2 tests seem to fail on ayo, but not on node. Not sure why yet.

**Comment by addaleax** [comment]
@qard the HTTP/2 issues should be fixed by #133 + this patch:

```diff
diff --git a/src/node_http2.cc b/src/node_http2.cc
index 99b909616152..19cbb13bb529 100644
--- a/src/node_http2.cc
+++ b/src/node_http2.cc
@@ -107,6 +107,8 @@ Http2Session::~Http2Session() {
 }
 
 void Http2Session::Close() {
+  if (prep_ == nullptr)
+    return;  // Avoid double close.
   if (!object().IsEmpty())
     ClearWrap(object());
   persistent().Reset();
```

**Comment by addaleax** [comment]
I went ahead and resolved conflicts and landed this + the patch above

Otherwise we’ll never be able to catch up ;)

Landed in fbd7c6e645e418be3ec82d38bacbc8e09a460731...45a1c8cf6384f5bcc81d834343c3ed9d78b97df3

**Comment by Qard** [comment]
Thanks! 🎉

**Pull request closed without merging**
