### PR TITLE
worker: implement vm.moveMessagePortToContext()

### PR DESCRIPTION
**Pull request by addaleax**
This should help a lot with actual sandboxing of JS code.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added (later/other PR)
- [x] commit message follows [commit guidelines](https://github.com/ayojs/ayo/blob/latest/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

worker

### CODE REVIEW

**Comment by ghost** [comment]
this is dependent on the main workers PR, which is why CI is failing, right?

**Comment by addaleax** [comment]
It’s not really dependent but a small bit of the build config changes would conflict if I didn’t align it with the main workers PR, yes

**Comment by TimothyGu** [comment]
Missing documentation.

**Comment by addaleax** [comment]
https://github.com/ayojs/ayo/pull/112/files#diff-060f40e7d677d8184f81dad0dde7e7ecR313 :)

**Review by TimothyGu — APPROVED** [review]
LGTM, though the move of EventEmitter to extras could be applied with this PR.

**Review by Qard — APPROVED** [review]

**Review by benjamingr — APPROVED** [review]

**Comment by addaleax** [comment]
Landed in 3ddde2c1eb4a188f5fc0d18c928b2fef53b41e50 :tada:

**Pull request closed without merging**
