### PR TITLE
Update from upstream: Sept 21

### PR DESCRIPTION
**Pull request by Qard**
Current tip of upstream master: https://github.com/nodejs/node/commit/cd1b55a94269cbb30e1ef7c4a67ce2500dbc6c08
Skipped due to contributor guide conflicts: https://github.com/nodejs/node/commit/bf1ca8fb2e4b92274cfc9cba837e75f7eee61b4f

### CODE REVIEW

**Review by Fishrock123 — APPROVED** [review]

**Comment by addaleax** [comment]
Hm, maybe I had some wrong info about the latest upstream commit? A lot of the patches in here are empty because they are already in `latest` … I don’t think that’s a problem, though

**Review by addaleax — APPROVED** [review]

**Comment by Qard** [comment]
Oh, you linked the wrong latest update PR in discord. Latest appears to be https://github.com/ayojs/ayo/pull/60, not https://github.com/ayojs/ayo/pull/52.

**Comment by addaleax** [comment]
@qard Oh, yeah, my bad. A simple rebase should fix that, but I think this would get resolved during landing anyway … 
¯\\\_(ツ)_/¯

**Comment by Qard** [comment]
Just redid it from the correct base. 😸

**Comment by Fishrock123** [comment]
heh, guess my approval was a tad quick

**Pull request merged**
