### PR TITLE
doc: Add helpful messaging to issue and PR template.

### PR DESCRIPTION
**Pull request by scotttrinh**
##### Checklist

- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

doc

---

Fixed links to Node documentation and added references to our Code of Conduct.

### CODE REVIEW

**Review by Qard — APPROVED** [review]

**Review by addaleax — APPROVED** [review]

**Review by stefee — APPROVED** [review]

**Comment by stefee** [comment]
Should we add something about `[ci skip]` to the PR template?

**Comment by srilq** [comment]
* to the PR template, to be clear

**Comment by scotttrinh** [comment]
It has to be [in the commit message](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build), yeah? Maybe it's best to add some notes about it to `CONTRIBUTING.md`?

**Comment by addaleax** [comment]
I think the better approach for that would be to do what @ljharb and maybe somebody else suggested, i.e. to detect whether only `.md` files have been touched or not and run `make test` only if that’s not the case.

(Fwiw, we do run the *linter* on our `.md` files for the API documentation)

**Comment by addaleax** [comment]
Landed in 8660eac9f6d935b4674ba053d5ab17b6fdd7e256 :)

**Pull request closed without merging**
