### PR TITLE
Update from upstream: Aug 25 2017

### PR DESCRIPTION
**Pull request by addaleax**
This is Node master rebased against our master, and I’d prefer to merge these commits by rebasing as well. Would everyone here be okay with that?

### CODE REVIEW

**Comment by sandfox** [comment]
seeing as it's early days and we haven't got a lot of our own changes (that will conflict) it seems a sensible option.

**Review by aqrln — APPROVED** [review]

**Comment by Fishrock123** [comment]
@addaleax will these commits sit ontop of our commits?

That does seem like a workable path although it will be hard to keep track of our commits this way without keeping some sort of list or branch?

**Comment by TimothyGu** [comment]
Another consideration is bisecting: if we end up with a lot of commits of our own *and* Node.js bisection can be difficult with huge merge commits. I experienced this while with FFmpeg (which merges from a fork called Libav), which ended up having one merge commit per upstream commit to help with this. Not sustainable, but somehow they've sustained that for a few years.

**Comment by TimothyGu** [comment]
(Rebasing is okay of course, but that work will grow exponentially over time.)

**Comment by zkat** [comment]
LGTM

**Comment by addaleax** [comment]
> @addaleax will these commits sit ontop of our commits?

Yes, that's what I'm thinking.

> That does seem like a workable path although it will be hard to keep track of our commits this way without keeping some sort of list or branch?

branch-diff should work well enough, I guess? Or you could always grep for commits that have an `ayojs/ayo` PR-URL field?

> Another consideration is bisecting: if we end up with a lot of commits of our own and Node.js bisection can be difficult with huge merge commits.

@TimothyGu I agree, this is one of the reasons why I'd like to avoid merge commits :)

**Comment by addaleax** [comment]
Landed in 7a10dc574bbb...2537dfedf6a4

**Comment by Fishrock123** [comment]
Makes sense. I've noted this strategy in #9.

**Pull request closed without merging**
