### PR TITLE
(doc) Remove Hal from Core team

### PR DESCRIPTION
**Pull request by Harrison-M**
I need to step down from the core team, as I am currently unable to participate in reviews, conversation, or meetings. I hope to return to the project eventually, but right now I don't have the time or energy to dedicate myself to this.

Love and best wishes to all of you. Sorry I forgot [skip ci] again on this.

##### Checklist

- [x] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/ayojs/ayo/blob/latest/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Review by addaleax — APPROVED** [review]
Once again, whenever you feel like you want to return, just raise your hand :)

**Review by Qard — APPROVED** [review]
You'll always be welcome here, should you choose to return in the future. 😸

**Review by ghost — APPROVED** [review]
thanks for all your previous engagement!

**Comment by sandfox** [comment]
Whatever works best for you @Harrison-M :-) , Take care of yourself and please don't be a stranger for too long!

**Comment by addaleax** [comment]
Landed in d8c7995fb20dad12a9c3edc00c6e6c23102fa3ab

**Pull request closed without merging**
