### PR TITLE
rfc: establish the website team

### PR DESCRIPTION
**Pull request by ghost**
hey! this PR adds a RFC for establishing an official team responsible for our website! if you're interested in this (even if you've never contributed to Node.js or Ayo.js). feel free to review this pull request or otherwise state your interest! we're looking for people who want to help us build our website!

### CODE REVIEW

**Comment by ghost** [comment]
a couple of questions that are left to be answered:

- how are members elected? does the team add members by its own will or can folks simply volunteer?
- how are rights over the repository managed otherwise? do people who contribute a lot, but aren't part of the team get write access?
- with what other (potential) teams should this team work together?

**Comment by NoahDragon** [comment]
Just wonder if a team member already has other roles, like moderator/core, can they join this team?

**Comment by mcataford** [comment]
I'm interested in pitching in if I can!

**Comment by abritinthebay** [comment]
Very interested in helping!

**Comment by Kataract** [comment]
Hi, I'm interested in helping.

**Comment by u1f408** [comment]
I'm interested!

**Comment by madhusudhand** [comment]
I can help.
I am a UI Dev. Worked with various frameworks such as Angular, Vue.

**Comment by z0al** [comment]
I'm very very interested :raised_hand:

**Comment by stefee** [comment]
I’d like to volunteer here as a full-stack (primarily front-end) junior-to-mid-level dev with too much free time.

**Comment by stefee** [comment]
@NoahDragon I’m pretty sure it’s only Core and Moderation that can’t have cross-over. Anyone can volunteer for sub-teams.

**Comment by varjmes** [comment]
Anyone can be a member of a sub team. And I'd like to be part of this team!

**Comment by eubenesa** [comment]
🙋🏻‍♂️

**Comment by pixiekat** [comment]
I'd volunteer for whatever I can, as I'm hoping to get more involved in Github.

**Comment by NoahDragon** [comment]
@srilq thanks for the clarification. Count me in.

**Comment by joshclow** [comment]
Add me to the interested list.

**Comment by moe-dizzle** [comment]
I'm interested! I would like more experience working on the backend in NodeJS, but I can work in AngularJS and VueJS.

**Comment by are** [comment]
I'd love to contribute to the website!

**Comment by Qard** [comment]
Should generation and hosting of docs markdown be included in website responsibilities?

**Comment by dentemple** [comment]
Hi, I'm also interested in helping out.  I have experience with React, so if you decide to go in that direction, I can certainly contribute!

**Comment by agrcrobles** [comment]
I'd love to help if the website is built with react

**Comment by ghost** [comment]
@Qard good question... would you think that it's a better idea if a separate docs team formed that also had hosting its content as a responsibility? the two teams would have to work together pretty closely in any way

**Comment by Qard** [comment]
Probably fine to just make it website responsibility for now and have a docs group take over if and when one arises.

**Review by addaleax — APPROVED** [review]

**Comment by ghost** [comment]
landed in 1a05c70ac81dc8fa1c0f161a58ace2ba9f536531! sorry for the holdup, i'll be creating a team and inviting everyone who's interested soon!

**Pull request closed without merging**
